<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_menu().
 */
function islandora_doi_framework_menu() {
  $items = array();
  $items['islandora/object/%islandora_object/manage/assign_doi'] = array(
    'title' => 'DOI',
    'access arguments' => array('assign DOIs to Islandora objects'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_doi_framework_manage_doi'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function islandora_doi_framework_permission() {
  return array(
    'manage DOIs for Islandora objects' => array(
      'title' => t('Manage DOIs for Islandora objects'),
      'description' => t('Assign and update DOIs for Islandora objects using the Islandora DOI Framework'),
    ),
  );
}

/**
 * Form definition for assigning a DOI.
 */
function islandora_doi_framework_manage_doi() {
  $form = array();
  $pid = arg(2);
  $object = islandora_object_load($pid);
  $form['islandora_doi_pid'] = array(
    '#type' => 'value',
    '#value' => $pid,
  );
  $dois = module_invoke_all('islandora_doi_framework_check_for_doi', $pid);
  $dois = array_unique($dois);
  if (count($dois)) {
    $dois = array_unique($dois);
    // Put any non-boolean values at beginning of array.
    rsort($dois);
  }

  $handlers = module_invoke_all('islandora_doi_framework_form_handlers');

  if (count($dois) && strlen($dois[0])) {
    $form['islandora_doi_framework_doi_exists_message'] = array(
      '#markup' => t("This object already has a DOI: !doi. Do you want to update the object's information associated with the DOI?",
        array('!doi' => $dois[0])),
      '#prefix' => '<div class="messages warning">',
      '#suffix' => '</div>',
      '#weight' => -10,
    );
    $form['islandora_doi_framework_update_doi'] = array(
      '#type' => 'submit',
      '#value' => 'Update DOI',
      '#submit' => array('islandora_doi_framework_update_doi_submit'),
      '#weight' => 10,
    );
    $form['islandora_doi_doi'] = array(
      '#type' => 'value',
      '#value' => $dois[0],
    );

    if (count($handlers)) {
      foreach ($handlers['update_doi']['submit'] as $handler) {
        $form['#submit'][] = $handler;
      }
    }
    $form['#submit'][] = 'islandora_doi_framework_manage_doi_update_submit_';

    return $form;
  }
  else {
    $form['islandora_doi_object_message'] = array(
      '#prefix' => '<div class="messages warning">',
      '#markup' => t("You are about to assign a DOI to object !pid (!label)",
        array('!pid' => $pid, '!label' => $object->label)),
      '#suffix' => '</div>',
      '#weight' => -10,
    );
    $form['islandora_doi_framework_assign_doi'] = array(
      '#type' => 'submit',
      '#value' => 'Assign DOI',
      '#weight' => 10,
    );

    if (count($handlers)) {
      foreach ($handlers['assign_doi']['submit'] as $handler) {
        $form['#submit'][] = $handler;
      }
    }
    $form['#submit'][] = 'islandora_doi_framework_manage_doi_assign_submit_';

    return $form;
  }
}

/**
 * Form submit handler. We provide a "default" form handler in case no
 * submodules provide any. We append a "_" to the end of the function name
 * so it doesn't overwrite the '#submit' property defined in the form.
 */
function islandora_doi_framework_manage_doi_assign_submit_($form, &$form_state) {
  module_load_include('inc', 'islandora_doi_framework', 'includes/utilities');
  $pid = $form_state['values']['islandora_doi_pid'];
  // We pass the form and form state into hook implementations so they
  // have access to the form values.
  if ($doi = islandora_doi_framework_mint_doi($pid, $form, $form_state)) {
    islandora_doi_framework_persist_doi($doi, $pid, $form, $form_state);
    $form_state['redirect'] = 'islandora/object/' . $pid;
  }
}

/**
 * Form submit handler. We provide a "default" form handler in case no
 * submodules provide any. We append a "_" to the end of the function name
 * so it doesn't overwrite the '#submit' property defined in the form.
 *
 * @todo: We need to settle on what 'update' means. Is it even possible to update a DOI? Maybe just the metadata?
 */
function islandora_doi_framework_manage_doi_update_submit_($form, &$form_state) {
  module_load_include('inc', 'islandora_doi_framework', 'includes/utilities');
  $pid = $form_state['values']['islandora_doi_pid'];
  $doi = $form_state['values']['islandora_doi_doi'];
  $updated = islandora_doi_framework_update($pid, $doi);
  if ($updated) {
    $form_state['redirect'] = 'islandora/object/' . $pid;
  }
}
