<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_islandora_doi_framework_check_for_doi().
 */
function islandora_doi_mods_islandora_doi_framework_check_for_doi($pid) {
  $object = islandora_object_load($pid);
  if ($object['MODS']) {
    $dom = new DOMDocument();
    $dom->loadXML($object['MODS']->content);
    $xpath = new DOMXPath($dom);
    $existing_doi_identifiers = $xpath->query("//mods:identifier[@type='doi']");
    if ($existing_doi_identifiers->length == 0) {
      return FALSE;
    }
    elseif ($existing_doi_identifiers->length == 1) {
      return $existing_doi_identifiers->item(0)->nodeValue;
    }
    else {
      watchdog(
        'islandora_doi_mods',
        'Object !pid has multiple (!count) DOIs in its MODS datastream.',
        array(
          '!pid' => $pid,
          '!count' => $existing_doi_identifiers->length,
        ),
        WATCHDOG_ERROR
      );
      return FALSE;
    }
  }
  else {
    watchdog(
      'islandora_doi_mods',
      'Object !pid has no MODS datastream.',
      array(
        '!pid' => $pid,
      ),
      WATCHDOG_ERROR
    );
    return FALSE;
  }
}

/**
 * Implements hook_islandora_doi_framework_persist().
 */
function islandora_doi_mods_islandora_doi_framework_persist($doi, $pid) {
  $object = islandora_object_load($pid);
  if ($object['MODS']) {
    // Add the DOI to the MODS in an <identifier type="doi"> element.
    $dom = new DOMDocument();
    $dom->loadXML($object['MODS']->content);
    $xpath = new DOMXPath($dom);

    module_load_include('inc', 'islandora_doi_mods', 'includes/utilities');
    if (!islandora_doi_mods_check_for_doi($pid)) {
      $doi_element_string = '<identifier type="doi">' . $doi . '</identifier>';
      $doi_element = $dom->createDocumentFragment();
      $doi_element->appendXML($doi_element_string);
      $dom->documentElement->appendChild($doi_element);

      // Replace the MODS datastream content.
      $mods_xml = $dom->saveXML();
      $object['MODS']->content = $mods_xml;
      drupal_set_message(t("DOI !doi successfully saved in !pid's MODS datastream.", array('!doi' => $doi, '!pid' => $pid)));
      return TRUE;
    }
    else {
      drupal_set_message(t("The MODS datastream for object !pid already contains a DOI.", array('!pid' => $pid)), 'error');
      return FALSE;
    }
  }
  else {
    drupal_set_message(t("There is no MODS datastream for object for object !pid to update with a DOI.", array('!pid' => $pid)), 'error');
    return FALSE;
  }
}
