<?php

/**
 * @file
 * Module file.
 *
 * This module is for testing and development purposes only. It should not be
 * used on a producation site.
 *
 * Modules that implement hook_islandora_doi_framework_persist() would
 * save the DOI in an object's MODS, or other datastream, or to a database
 * table. This sample module simply saves it to a text file. This module
 * can be used to "persist" DOIs during the development and testing of
 * Islandora DOI Framework submodules that "mint" DOIs.
 */

define('ISLANDORA_DOI_FRAMEWORK_SAMPLE_PERSIST_OUTPUT_PATH', '/tmp/dois_sample_persist.txt');
define('ISLANDORA_DOI_FRAMEWORK_SAMPLE_PERSIST_SUFFIX', '10.99999/');

/**
 * Implements hook_islandora_doi_framework_check_for_doi().
 */
function islandora_doi_framework_sample_persist_islandora_doi_framework_check_for_doi($pid) {
  if (file_exists(ISLANDORA_DOI_FRAMEWORK_SAMPLE_PERSIST_OUTPUT_PATH) &&
    is_readable(ISLANDORA_DOI_FRAMEWORK_SAMPLE_PERSIST_OUTPUT_PATH)) {
    $persisted_dois = file(ISLANDORA_DOI_FRAMEWORK_SAMPLE_PERSIST_OUTPUT_PATH, FILE_IGNORE_NEW_LINES);
    $doi = ISLANDORA_DOI_FRAMEWORK_SAMPLE_PERSIST_SUFFIX . $pid;
    if (in_array($doi, $persisted_dois)) {
      return $doi;
    }
    else {
      return FALSE;
    }
  }
  else {
    watchdog(
      'islandora_doi_framework_sample_persist',
      'Cannot read from DOI file.',
      array(
        '!pid' => $pid,
      ),
      WATCHDOG_ERROR
    );
    return FALSE;
  }
}

/**
 * Implements hook_islandora_doi_framework_persist().
 */
function islandora_doi_framework_sample_persist_islandora_doi_framework_persist($doi, $pid) {
  if ($existing_doi = islandora_doi_framework_sample_persist_islandora_doi_framework_check_for_doi($pid)) {
    drupal_set_message(t("Object !pid already has a sample/test DOI (!doi).", array('!pid' => $pid, '!doi' => $existing_doi)), 'error');
    return FALSE;
  }
  else {
    // Write the DOI to the output file.
    if (file_put_contents(ISLANDORA_DOI_FRAMEWORK_SAMPLE_PERSIST_OUTPUT_PATH, trim($doi) . PHP_EOL, FILE_APPEND)) {
      drupal_set_message(t("Sample/test DOI !doi successfully saved to the output file.", array('!doi' => $doi, '!pid' => $pid)));
      return TRUE;
    }
    else {
      drupal_set_message(t("Cannot write sample/test DOI for object !pid to the output file.", array('!pid' => $pid)), 'error');
      return FALSE;
    }
  }
}

/**
 * Implements hook_islandora_doi_framework_update().
 */
function islandora_doi_framework_sample_persist_islandora_doi_framework_update($pid, $doi) {
  // We just return TRUE here since the updated DOI will be the same as the existing one.
  return 'url';
}
