<?php

/**
 * @file
 * This file contains all install related hooks.
 */

/**
 * Implements hook_uninstall().
 */
function islandora_doi_datacite_uninstall() {
  $variables = array(
    'islandora_doi_datacite_api_url',
    'islandora_doi_datacite_prefix',
    'islandora_doi_datacite_suffix_source',
    'islandora_doi_datacite_username',
    'islandora_doi_datacite_password',
    'islandora_doi_datacite_combine_creator',
  );
  array_walk($variables, 'variable_del');
}
