<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_islandora_doi_framework_check_for_doi().
 */
function islandora_doi_ddi_islandora_doi_framework_check_for_doi($pid) {
  $object = islandora_object_load($pid);
  if ($object['DDI']) {
    $dom = new DOMDocument();
    $dom->loadXML($object['DDI']->content);
    $existing_doi_identifiers = $dom->getElementsByTagName('IDNo');
    if ($existing_doi_identifiers->length == 0) {
      return FALSE;
    }
    elseif ($existing_doi_identifiers->length == 1) {
      return $existing_doi_identifiers->item(0)->nodeValue;
    }
    else {
      watchdog(
        'islandora_doi_ddi',
        'Object !pid has multiple (!count) DOIs in its DDI datastream.',
        array(
          '!pid' => $pid,
          '!count' => $existing_doi_identifiers->length,
        ),
        WATCHDOG_ERROR
      );
      return FALSE;
    }
  }
  else {
    watchdog(
      'islandora_doi_ddi',
      'Object !pid has no DDI datastream.',
      array(
        '!pid' => $pid,
      ),
      WATCHDOG_ERROR
    );
    return FALSE;
  }
}

/**
 * Implements hook_islandora_doi_framework_persist().
 */
function islandora_doi_ddi_islandora_doi_framework_persist($doi, $pid) {
  $object = islandora_object_load($pid);
  if ($object['DDI']) {
    // Add the DOI to the DDI in an <identifier type="doi"> element.
    $dom = new DOMDocument();
    $dom->loadXML($object['DDI']->content);
    $xpath = new DOMXPath($dom);

    if (!islandora_doi_ddi_islandora_doi_framework_check_for_doi($pid)) {
      // This is typically awful PHP but seems to work
      // Why I can't deserialize this all from one line I'll never know.
      $doi_element_string = '<IDNo agency="doi">' . $doi . '</IDNo>';
      $doi_element = $dom->createDocumentFragment();
      $doi_element->appendXML($doi_element_string);
      $codeBook = $dom->getElementsByTagName('codeBook')->item(0);
      $docDscr = $dom->createElement("docDscr");
      $docDscrNode = $codeBook->appendChild($docDscr);
      $citation = $dom->createElement("citation");
      $citationNode = $docDscrNode->appendChild($citation);
      $titlStmt = $dom->createElement("titlStmt");
      $titlStmtNode = $citationNode->appendChild($titlStmt);
      $titlStmt->appendChild($doi_element);

      // Replace the DDI datastream content.
      $ddi_xml = $dom->saveXML();
      $object['DDI']->content = $ddi_xml;
      drupal_set_message(t("DOI !doi successfully saved in !pid's DDI datastream.", array('!doi' => $doi, '!pid' => $pid)));
      return TRUE;
    }
    else {
      drupal_set_message(t("The DDI datastream for object !pid already contains a DOI.", array('!pid' => $pid)), 'error');
      return FALSE;
    }
  }
  else {
    drupal_set_message(t("There is no DDI datastream for object for object !pid to update with a DOI.", array('!pid' => $pid)), 'error');
    return FALSE;
  }
}
