<?php

/**
 * @file
 * Module file.
 *
 * DOIs minted by this module are not real DOIs. Their purpose is solely
 * to assist in the development and testing of modules that persist (save)
 * real DOIs to an object. These DOIs should *not* be persisted to production
 * objects.
 *
 * Real DOIs must be minted via a registration agency
 * (http://www.doi.org/registration_agencies.html). The suffix (the part to
 * the right of the /) is assigned by the organization that wishes to register
 * DOI names (publisher, university, etc.). The preix (the part to the left
 * of the /) is assigned to the publisher, university, etc. by the
 * registration agency. We use the fake prefix 10.99999 in this module.
 */

/**
 * Implements hook_form_alter().
 *
 * This example shows how a module can inject its own form elements or
 * otherwise alter the islandora_doi_framework_manage_doi form provided by
 * the main framework module. In this example, all we use the form value for
 * is to display it to the user on form submission.
 */
function islandora_doi_framework_sample_mint_form_islandora_doi_framework_manage_doi_alter(&$form, $form_state, $form_id) {
  $form['islandora_doi_framework_sample_mint_doi_color'] = array(
    '#type' => 'select',
    '#title' => t("Select a color name to display in the 'Hello' test message."),
    '#options' => array('blue' => 'blue', 'green' => 'green', 'yellow' => 'yellow'),
  );
}

/**
 * Implements hook_islandora_doi_framework_form_handlers().
 */
function islandora_doi_framework_sample_mint_islandora_doi_framework_form_handlers() {
  return array(
    'assign_doi' => array(
      'validate' => array(),
      'submit' => array('islandora_doi_framework_sample_mint_assign_doi_submit'),
     ),
    'update_doi' => array(
      'validate' => array(),
      'submit' => array('islandora_doi_framework_sample_mint_update_doi_submit'),
     ),
  );
}

/**
 * Form submit handler.
 */
function islandora_doi_framework_sample_mint_assign_doi_submit($form, &$form_state) {
  drupal_set_message(t("Hello from the Islandora DOI Framework sample mint module. You chose !color.", array('!color' => $form_state['values']['islandora_doi_framework_sample_mint_doi_color'])));
}

/**
 * Implements hook_islandora_doi_framework_mint().
 */
function islandora_doi_framework_sample_mint_islandora_doi_framework_mint($pid, $form, $form_state) {
  $doi = '10.99999/' . $pid;
  drupal_set_message(t("Sample/test DOI !doi assigned to object !pid.", array('!pid' => $pid, '!doi' => $doi)));
  return $doi;
}
